[package]
name = "rbl"
version = "0.1.0"
authors = ["Jiajie Chen <noc@jiegec.ac.cn>"]
edition = "2018"

[dependencies]
xmas-elf = "0.6"
riscv = "0.5"
device_tree = { git = "https://github.com/jiegec/device_tree-rs" }

[build-dependencies]
cc = "1.0"